{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Error Implementations","modules":[{"name":"CryptoTrackerApp"}]},"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp\/NetworkManager\/NetworkError\/localizedDescription"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/cryptotrackerapp\/networkmanager\/networkerror\/error-implementations"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp\/NetworkManager\/NetworkError\/Error-Implementations"},"hierarchy":{"paths":[["doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp","doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp\/NetworkManager","doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp\/NetworkManager\/NetworkError"]]},"references":{"doc://Currency.CryptoTrackerApp/documentation/CryptoTrackerApp/NetworkManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp\/NetworkManager","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkManager"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkManager"}],"url":"\/documentation\/cryptotrackerapp\/networkmanager","title":"NetworkManager"},"doc://Currency.CryptoTrackerApp/documentation/CryptoTrackerApp":{"identifier":"doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/cryptotrackerapp","kind":"symbol","title":"CryptoTrackerApp"},"doc://Currency.CryptoTrackerApp/documentation/CryptoTrackerApp/NetworkManager/NetworkError/localizedDescription":{"title":"localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp\/NetworkManager\/NetworkError\/localizedDescription","role":"symbol","url":"\/documentation\/cryptotrackerapp\/networkmanager\/networkerror\/localizeddescription","abstract":[]},"doc://Currency.CryptoTrackerApp/documentation/CryptoTrackerApp/NetworkManager/NetworkError":{"type":"topic","abstract":[],"identifier":"doc:\/\/Currency.CryptoTrackerApp\/documentation\/CryptoTrackerApp\/NetworkManager\/NetworkError","kind":"symbol","navigatorTitle":[{"text":"NetworkError","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkError"}],"url":"\/documentation\/cryptotrackerapp\/networkmanager\/networkerror","title":"NetworkManager.NetworkError"}}}